### ISSUE TITLE
Dorothy - Mozart-Oz  + OPI in Docker

### ISSUE THREAD

**Issue by richarah** [veggiemonk/awesome-docker#1022]
Hi,

I wish to contribute a new project to the list. If anything is missing or could be improved in the entry, please do not hesitate to let me know.

#### Category
Docker Images > Base Tools

#### What it is
A Docker image for  running Oz and the OPI from within a container environment, either standalone or as part of a CDE - e.g. using VSCode's [Remote - Containers](https://code.visualstudio.com/docs/remote/containers) extension.

#### What it's for
Oz and the OPI suffer serious compatibility issues on certain machines - notably OPI crashes upon startup, Ozcar debugger issues, and code that compiles flawlessly on other machines refusing to compile on those affected.

By packaging Oz and the OPI within the self-contained, standardised environment of a Docker container, the Dorothy project aims to resolve these machine- and platform-specific issues.

**REPO**:
https://github.com/richarah/dorothy

**DESCRIPTION**
Mozart-Oz + OPI in Docker

**AUTHOR**:
Richard Alexander Haydon @richarah
https://github.com/richarah

Or directly write it:
```markdown
[dorothy](https://github.com/richarah/dorothy) - Mozart-Oz + OPI in Docker. By [@richarah](https://github.com/richarah)
```

**Comment by veggiemonk** [comment]
Hi @richarah, thank you for contributing.

I looked at the project and it seems it's not really related to the topic of "building containers" but rather, it is a tool inside a container. We decided a long time ago that this would be too much to handle here, as you can imagine how long the list would be if we had to list all the tools that are containerized these days.

What I would recommend is to make a pull-request to the original project. If I'm not mistaken, it is this one: https://github.com/mozart/mozart2

I hope this helps and happy contributing in open source.
