### ISSUE TITLE
A cli tools to manage docker-compose projects from everywhere.

### ISSUE THREAD

**Issue by FabienD** [veggiemonk/awesome-docker#1065]
Hi,

I would like to add a link.

**REPO**: https://github.com/FabienD/docker-stack

**DESCRIPTION**:  The project provides a cli tools "dctl" that can manage your projects using docker-compose file(s) from everywhere in the terminal.  The project provides the main docker compose commands, with the same arguments. 
The project also provides a collection of docker files for web developers.

**AUTHOR**: FabienD

**Comment by mashb1t** [comment]
Hey @FabienD,
feel free to create a merge request which we'll then review.
