### ISSUE TITLE
Broken hyperlinks

### ISSUE THREAD

**Issue by ndsvw** [veggiemonk/awesome-docker#1072]
Hello, I found multiple broken hyperlinks. Some of them are relative links that don't work:
- [ ] grammarly (file: README.md, status code: 404)
- [ ] crazy-max (file: README.md, status code: 404)
- [ ] deepfence (file: README.md, status code: 404)
- [ ] istio (file: README.md, status code: 404)
- [ ] g31s (file: README.md, status code: 404)
- [x] https://github.com/prologic/autodock (file: README.md, status code: 404)
- [x] Sandbox (file: README.md, status code: 404)
- [x] ahmetalpbalkan (file: README.md, status code: 404)
- [x] https://github.com/konstruktoid/Docker/blob/master/Security/CheatSheet.adoc (file: README.md, status code: 404)
- [x] http://docker-br.herokuapp.com (file: README.md, status code: 404)

**Comment by agebhar1** [comment]
Thanks for the hint @ndsvw. We will improve it.
