### ISSUE TITLE
Xpipe - management registry for ssh/docker

### ISSUE THREAD

**Issue by h1ght** [veggiemonk/awesome-docker#1106]
Hi,

I would like to add a link.
https://github.com/xpipe-io/xpipe

**REPO**:
https://github.com/xpipe-io/xpipe

**DESCRIPTION**:
neat "server- manager" for ssh/docker and more stuff. directly able to join docker container cli/file system.

**AUTHOR**:
@xpipe-io 
https://xpipe.io/

**Comment by mashb1t** [comment]
Hey @h1ght, feel free to create a pull request, which we'll then review. You can just fork the repository, add the tool and description and follow the PR template when creating one afterwards.
