### ISSUE TITLE
Add SparkView

### ISSUE THREAD

**Issue by JulianHochgesang** [veggiemonk/awesome-docker#1116]
Hi,

I would like to add a link.

**REPO**:
https://github.com/beyondssl/sparkview-container

**DESCRIPTION**:
SparkView is a smart and easy remote access solution that works from any device with a browser. No VPN client needs to be installed, simply deploy the Docker image in your DMZ. Access VMs, desktops, servers or applications anytime and from anywhere, without complex and costly client roll-outs or user management.

**AUTHOR**:
https://github.com/beyondssl

**Comment by agebhar1** [comment]
Hi @JulianHochgesang,

thank you for the suggestion. You're very welcome to create a pull request.

**Comment by agebhar1** [comment]
Closed by #1117.
