### ISSUE TITLE
Add goManageDocker

### ISSUE THREAD

**Issue by ajayd-san** [veggiemonk/awesome-docker#1128]
Hi,

I would like to add a link.

**REPO**: https://github.com/ajayd-san/gomanagedocker

**DESCRIPTION**: TUI tool to view and manage your docker images, containers, and volumes blazingly fast. Other features include the ability to `exec` into any container and the ability to perform `docker scout` on any image with a single keystroke. 

**AUTHOR**:  https://github.com/ajayd-san

**Comment by mashb1t** [comment]
@ajayd-san Looks similar to other tools like lazydocker. Feel free to create a PR, category https://github.com/veggiemonk/awesome-docker?tab=readme-ov-file#terminal-ui
