### ISSUE TITLE
Twitter integration broken, move to mastodon?

### ISSUE THREAD

**Issue by popey** [veggiemonk/awesome-docker#1137]
Hi. I recently contributed [pr 1134](https://github.com/veggiemonk/awesome-docker/pull/1134) in which the bot [says](https://github.com/veggiemonk/awesome-docker/pull/1134#issuecomment-2226420027) that it'll be announced on twitter.

That integration seems broken, as there's been nothing on the Twitter [timeline](https://twitter.com/awesome_docker) for over a year. I presume it's been broken since API changes happened on Twitter.

Is it perhaps worth creating an account over on Mastodon - or some other platform - to raise awareness and celebrate contributions, and the awesome-docker repo?

At the absolute minimum, it's probably worth removing mentions of twitter both in the readme and the bot replies, if it's not working?

**Comment by veggiemonk** [comment]
Hi @popey,

Thanks for bringing this to our attention. If I remember correctly, @vegasbrianc was the one to set it up back then. 

See #1138 for the changes. 

Personally, I'm already notified of all the changes on GitHub because I'm a reviewer for PRs but I'm happy to help to send updates somewhere.

What would you recommend? 
Have you done those integration before? 
Can you recommend a tool or an API to facilitate that? :)

**Comment by popey** [comment]
I guess it comes down to whether there's actual value in announcing repo updates to social media. I just scrolled back through the twitter posts from the account and it gets near zero engagement. 

So maybe it's just not worthwhile? I don't know.

I know that it's possible to setup a bot account on a mastodon server, such as https://botsin.space/ and https://mastodon.bot/ and get an API then use a GitHub action like [mastodon-send](https://github.com/marketplace/actions/mastodon-send) can be added to this repo to announce over there.

But again, I don't know how worthwhile it is, sorry. 🤷

**Comment by veggiemonk** [comment]
Indeed, thanks for confirming that there isn't much value added by having that on social media. Let's merge the PR that removes the mention. Thank you for your insight.
