### ISSUE TITLE
swarm-ansible

### ISSUE THREAD

**Issue by LombardiDaniel** [veggiemonk/awesome-docker#1145]
Hi,

I would like to add a link.

**REPO**: https://github.com/LombardiDaniel/swarm-ansible

**DESCRIPTION**: Rapidly booststrap a production-ready cluster with docker swarm

**AUTHOR**: LombardiDaniel(me)

**Comment by veggiemonk** [comment]
It has been added: https://github.com/veggiemonk/awesome-docker?tab=readme-ov-file#deployment-and-infrastructure

Thank you for your contribution.
