### ISSUE TITLE
contributor-over-time chart provided by api7.ai is out of service, suggest to remove it from README

### ISSUE THREAD

**Issue by yzeng25** [veggiemonk/awesome-docker#1152]
Hi,

I would like to add a link.

https://github.com/veggiemonk/awesome-docker?tab=readme-ov-file#contributor-over-time

**REPO**: [veggiemonk/awesome-docker](https://github.com/veggiemonk/awesome-docker)

**DESCRIPTION**:

contributor-over-time chart provided by api7.ai is out of service, suggest to remove it from README

**Comment by veggiemonk** [comment]
Thanks a lot. The problem is now fixed. 
Much appreciated 🙏
