### ISSUE TITLE
Should the depricated links keep in this list?

### ISSUE THREAD

**Issue by pedrro** [veggiemonk/awesome-docker#139]
Hey guys, have in this list some links that are deprecated, should this link keep in the list? I can open a PR to review that deprecated links.

**Comment by veggiemonk** [comment]
Yes sure, PR are always welcome.
Can you tell us what are the deprecated links?

**Comment by pedrro** [comment]
I created a pr to show for you the deprecated links, enjoy!

**Comment by veggiemonk** [comment]
merged. Thanks again.
