### ISSUE TITLE
Dockerboard seems dead

### ISSUE THREAD

**Issue by senk** [veggiemonk/awesome-docker#160]
"Dockerboard
Refactor, beginning with 2015-12-01T00:00:00Z." states the Readme.md fron repo.

Anyone further information about this?

https://github.com/dockerboard/dockerboard

**Comment by jacktuck** [comment]
+1

Was it ever alive?

**Comment by veggiemonk** [comment]
It seems totally dead indeed. It is removed in a60c48d9d282d857c3980335898592a3cd9847e3

Thanks for letting us know @senk @jacktuck :smile:
