### ISSUE TITLE
new category ?

### ISSUE THREAD

**Issue by veggiemonk** [veggiemonk/awesome-docker#177]
Pumba: Chaos testing tool for Docker https://github.com/gaia-adm/pumba

add a new category: TESTING

**Comment by vegasbrianc** [comment]
Sounds like a good category to have for sure!

**Comment by veggiemonk** [comment]
@vegasbrianc true, but I cannot find any other project for testing... any ideas?

**Comment by vegasbrianc** [comment]
I think you are right as it is a blurred line between testing and CI/CD at the moment with Docker. Maybe we should revisit this in a few months.

**Comment by veggiemonk** [comment]
sounds good :ok_hand:
