### ISSUE TITLE
Consider adding 'jeff1evesque/machine-learning'

### ISSUE THREAD

**Issue by jeff1evesque** [veggiemonk/awesome-docker#224]
Just curious if my [repository](https://github.com/jeff1evesque/machine-learning) could be added to the [`README.md`](https://github.com/veggiemonk/awesome-docker/blob/master/README.md) of this project, for similar reasons as docker's [Project using docker](https://github.com/docker/docker/wiki/Projects-using-docker#projects) wiki page:

>[How to incorporate python unit testing via docker containers, using continuous integration](https://github.com/jeff1evesque/machine-learning) (see [.travis.yml#L101-L112](https://github.com/jeff1evesque/machine-learning/blob/78384feb5477464dba4a48b96dbfc01e1d39b0f6/.travis.yml#L101-L112))

Later, I intend to build a more robust development environment, where I would incorporate docker containers, within the current existing vagrant environment.  If my project is reasonable, could someone recommend which section I should commit my repository reference into.  I was thinking either adding my repository to [Continuous Integration / Continuous Delivery](https://github.com/veggiemonk/awesome-docker/blob/master/README.md#continuous-integration--continuous-delivery), or adding a new *Machine Learning* section.

**Comment by vegasbrianc** [comment]
Hi @jeff1evesque First, your project is very impressive. I could see a ton of use cases for your tool and might have to give it a go myself but the awesome-docker list is currently only listing Docker Tools.

If in the future, if you find a use case which your project could use your machine learning capability on containers or the ecosystem we would be happy to accept it. This actually sounds very interesting. I was going to suggest to submit to the awesome machine learning list but you seem to be already listed.

Thanks again and good luck with your project.

Brian
