### ISSUE TITLE
The O'Reilly article "Swarm v. Fleet v. Kubernetes v. Mesos" is incomplete

### ISSUE THREAD

**Issue by eelkevdbos** [veggiemonk/awesome-docker#259]
Visiting [this](https://www.oreilly.com/ideas/swarm-v-fleet-v-kubernetes-v-mesos) article, I noticed an abrupt ending at the second chapter (Fleet). I think we should remove the article or contact O'Reilly. Would love to read the full story though.

**Comment by vegasbrianc** [comment]
If you login to O'Reilly you should be able to see the entire article. It is still free. <img width="631" alt="screen shot 2017-01-09 at 12 43 17" src="https://cloud.githubusercontent.com/assets/674790/21765446/40e65524-d669-11e6-9036-df2b3c3bf39c.png">

**Comment by eelkevdbos** [comment]
Thanks for pointing out @vegasbrianc 

Apparently, running an aggressive ad-blocker also blocks the paywall / login dialog.
