### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by veggiemonk** [veggiemonk/awesome-docker#279]
Hi,

don't forget that you can chat or leave a message on the chat in gitter:

https://gitter.im/veggiemonk/awesome-docker

ping @vegasbrianc @gesellix @dmitrytokarev

**Comment by X4** [comment]
Here's someone with another list:
https://github.com/hangyan/docker-resources

**Comment by veggiemonk** [comment]
Thank you @X4 

It is an interesting link. 
It looks like the repo you mentioned is an old fork from this repo. 
I tried a few links and half of them were outdated and/or broken.

In this repo, every links are tested (although it does not mean that they all work all the time).
There are also a lot of articles and `awesome-docker` goal is to focus exclusively on projects and services related to Docker. 
In the link you gave, there might be a few projects that are not in `awesome-docker`. They will be reviewed for quality. Thanks for letting us know.

Maybe we could even join forces, are you related to that project?

**Comment by gesellix** [comment]
> Maybe we could even join forces, are you related to that project?

ping @X4

**Comment by X4** [comment]
Sorry, for the late reply I wasn't in town and also had fever. I am not related to the project though.
