### ISSUE TITLE
Octohost project is no longer actively maintained

### ISSUE THREAD

**Issue by devhkr** [veggiemonk/awesome-docker#311]
Hi,

according to the repo's README page as well as their website, the project is inactive.

[https://github.com/octohost/octohost](https://github.com/octohost/octohost)

**Comment by agebhar1** [comment]
@devhkr thanks for the info - PR is welcome to add deprecation/remove from list

**Comment by devhkr** [comment]
Ok, just submitted PR #312

**Comment by agebhar1** [comment]
closed by PR #312
