### ISSUE TITLE
Please add to Monitoring & Logging Services 

### ISSUE THREAD

**Issue by ashley03** [veggiemonk/awesome-docker#318]
Hi @veggiemonk,

I would like to add a link. 

CA Technologies has  great Docker Monitoring capabilities and believe it should be included in the monitoring & logging services list. 

**DESCRIPTION**:   [CA Technologies Docker Monitoring](url): https://www.ca.com/us/products/docker-monitoring.html] - Agile Operations solutions from CA deliver the modern Docker monitoring businesses need to accelerate and optimize the performance of microservices and the dynamic Docker environments running them.

**AUTHOR**: @Ashley03

Thank you!

**Comment by agebhar1** [comment]
Hi @ashley03 thanks for the link - maybe you open a **P**ull **R**equest with the added link?

**Comment by veggiemonk** [comment]
@ashley03 we have no way of evaluating your services. 

It is not clear how to set it up of even how to use it. 
Sorry but it needs improvement. Please read the contributing guidelines (the file `CONTRIBUTING.md` and welcome on github 

Thank you
