### ISSUE TITLE
docker sync now supports windows and linux

### ISSUE THREAD

**Issue by EugenMayer** [veggiemonk/awesome-docker#339]
docker-sync now also supports windows and linux, not only OSX - might be worth adding

**Comment by agebhar1** [comment]
hi @EugenMayer thanks for the update! You're welcome for a PR with the changes for your »docker sync«. If you're busy, let us know - we're happy to change it for you.

**Comment by EugenMayer** [comment]
sure, pr opened, guess we can close this one - you decide :)

**Comment by agebhar1** [comment]
Thx @EugenMayer !

The awesome docker team
@vegasbrianc @gesellix @dmitrytokarev @veggiemonk @agebhar1 @devhkr
