### ISSUE TITLE
Swarmpit.io

### ISSUE THREAD

**Issue by jinjanko** [veggiemonk/awesome-docker#378]
Hi,

I would like to add a link to our beautiful project http://swarmpit.io/

**https://github.com/swarmpit**:

**Lightweight Docker Swarm orchestration. Swarmpit provides nice & clean way to manage your Docker Swarm cluster with various handful features such Service management, Smart search, Shared access, Private registries and more to come soon**:

**https://github.com/nohaapav**:

**Comment by holms** [comment]
I'm voting with all my five hands to accept this, finally someone did it!

**Comment by jinjanko** [comment]
SORRY GUYS, it's a duplicity :) pavol already asked for adding us

**Comment by veggiemonk** [comment]
@jinjanko @holms yes pull request are the fatest way to get feedback,
see #375
