### ISSUE TITLE
Refactoring: list of sections

### ISSUE THREAD

**Issue by veggiemonk** [veggiemonk/awesome-docker#393]
So far we have:

- [ ] Continuous Integration / Continuous Delivery
   - [ ] CI Services
- [ ] Deployment and Infrastructure
- [ ] Developer Tools: API to access docker via code
- [ ] Development Environments: tools to help developing with docker
- [ ] Dockerfile: example to help build lean and clean docker images
- [ ] Garbage Collection: to keep your dev env clean
- [ ] Hosting Images (registries)
- [ ] Image Builder: to build those lean and clean docker images
- [ ] Linter / Validator: gives tips on how to build lean and clean docker images
- [ ] Local Container Manager
- [ ] Monitoring & Logging
   - [ ] Monitoring & Logging Services
- [ ] Networking
- [ ] PaaS
- [ ] Remote Container Manager / Orchestration
- [ ] Reverse Proxy
- [ ] Security
- [ ] Serverless
- [ ] Service Discovery
- [ ] CaaS - Services for running containers
- [ ] Terminal User Interface
- [x] Testing
- [ ] Utilities <--- this one is a really bad name!
- [ ] Volume management and plugins
- [ ] Web Interface

---

Local container manager, web interface and terminal user interface should be sub-section under the section called "Docker interface" or "Docker UI". This section is typically for people who don't like command line tools and/or just want to try docker to see what it is.

Everything related to building, linting images should be under one section called "Docker images". This section would be for those who are already using docker and want to build better images for example.

Everything related to developing with docker (dev env, dev tools, utilities(?) ) should be under one section called "Developing with Docker" (see how long I looked for a good name :p). This section is for those who want to build a project by using docker for example.

And the rest should be under one section called "Managing Docker containers" or something similar.
This section would be for DevOps who already manage docker containers in production.

Those are the 4 main sections so far, would love to hear other opinions on that.

**Comment by veggiemonk** [comment]
@Moshe-Immerman Nice job !!!

**Comment by Moshe-Immerman** [comment]
Maybe we should break it down by use case e.g.

Running
   + Building
      + System tools
   + Composition
   + CLI
   + Orchestration
   + Hooks
   + Web
   + Wrappers (e.g. dexec, udocker, dray, fugu etc)
Development Environments
Development on Docker
   + API Clients
   + Service Discovery
   + Linting
   + Serverless
Deployment
  + Registries
  + CaaS
  + PaaS
  + Monitoring
  + Networking

**Comment by devhkr** [comment]
Good initiative @Moshe-Immerman. 

However, before we merge pending PRs, we should all agree on (sub)categories. Then we can refactor, otherwise it's getting messy.

Another point is that we should describe what each (sub)category is all about. A good starting point would be like [awesome-java](https://github.com/akullpp/awesome-java)

**Comment by agebhar1** [comment]
another approach - or in addition - could be tagging by tags, if a project doesn't fit exactly into one category

**Comment by veggiemonk** [comment]
@agebhar1 Good idea but I have a little bit of trouble when it comes to actual use cases.
Do you have an example? What would be the tags in our case ?

**Comment by Moshe-Immerman** [comment]
I like the concept of tagging, but perhaps using icons instead of text otherwise we run the risk of going over 1 line. 

e.g. awesome-java uses: 

Commercial: ![](https://cdn.rawgit.com/akullpp/23246ca832bda82bb505230bf3538e2a/raw/d9bcdb769bf025292f9c6bc1290f01f1fcd1f864/commercial.svg)  

and I can think of a few more:

- ancient (but still awesome/relevant)
- CLI / terminal
- library
- beta / upcoming
- docs / tutorial

**Comment by veggiemonk** [comment]
I like this icon/tagging idea. 


For the sections, if we are going to sort them by use case, the name of the subsection should also be a use case, not just a category/type !
So I don't really like this separation because it is based on the projects, not really on the people who are looking for those projects.

### I would like for us to give a little thought on **WHO** it would help rather then **WHAT** it is... Because projects can pivot/evolve/...

But here is some ideas:

**~~Running & Deployment~~** --> **Managing Containers**  
   + Composition --> Container Composition
   + ~~CLI~~ <-- what is the purpose of this subsection, this is a category of projects, not really a use case.
   + Terminal User Interface: to help manage docker container from a terminal
   + ~~Web~~ <-- Docker web UI : to help manage docker container from a browser
   + ~~Setup / Installation~~ --> Deployment and Infrastructure <--- This should be split or renamed
   + Service Discovery
   + Orchestration <-- might cause an overlap with PaaS, how to differentiate the 2?
   + CaaS  (do we have any project that is not a paying service there? )
   + PaaS
   + Monitoring
   + Networking
   + Reverse Proxy
   + Security
   + Volumes management / Data


**Docker Images** 
   + Building
   + ~~System tools~~ for lack of a better name: project to help containerize an app --> Inside Container Tools ? please help with the naming because System tools means nothing to me.
   + Dockerfile: example to help build lean and clean docker images
   + Linting
   + Registries

**Development ~~on~~ with Docker**
   + API Clients
   + CI/CD
   + Development Environments
   + Garbage Collection: to keep your dev env clean
   + ~~Hooks~~ <-- Docker Event Hooks
   + Serverless
   + Testing
   + Wrappers (e.g. dexec, udocker, dray, fugu etc)

**Services based on Docker** ($$$)
   + CI/CD
   + Monitoring
   + CaaS
   + Registries
   + Security (?)
   + PaaS



**ICONS/TAGS**
Commercial
Premium/Free trial
Open Source
Library
CLI/Terminal
Web UI
Beta / Upcoming
Great Documentation
Heart (if some of us have a project crush ;-) 



This is not perfect but if we organize this list according to what people are looking for, it is going to make our lives easier. 
By the way, how is the Moby project organized ? Because they might have given some thought about that and we might want to learn from what they struggled with.

Feel free to reorder/change/comment/whatever so that we get the best ideas...

**Comment by vegasbrianc** [comment]
What about naming the section Managing Containers -> Container Operations?

**Comment by veggiemonk** [comment]
See @Moshe-Immerman PR for the changes  (good job!) #397

**Comment by devhkr** [comment]
In my opinion, we should continue discussing here instead of opening new PR as it's going to be messy. The comments here are editable anyway.

**Comment by Moshe-Immerman** [comment]
@devhkr The comments may be editable, but the comments themselves are not comment-able so it is really difficult to discuss each line

**Comment by devhkr** [comment]
@Moshe-Immerman I agree with you and I see your point.

However, a PR could also lead to long discussions. I know, this is where everyone can comment on code-lines. Furthermore, what if someone has a very different idea/suggestion? Long discussions start again. In my opinion, we should start small keeping the following comments by @veggiemonk in mind:

>We should give a little thought on WHO it would help rather then WHAT it is... 

>In case of doubt, just imagine yourself as someone who doesn't know much about docker and is looking for a nice, simple [insert name of the section here]... That's what awesome lists are for...

We all value each other's contribution and time, but making smaller things speed up review time and it’s easier for the reviewers to understand the context and reason with the logic.

**Comment by veggiemonk** [comment]
@devhkr nicely put

**Comment by Moshe-Immerman** [comment]
@devhkr in terms of resources I am of the belief they should be inclined e.g. Under the Docker images section we have both awesome docs/videos with tags and awesome software) however in the spirit of keepings things small I think the resources section should be left for separate issue/pr

**Comment by veggiemonk** [comment]
OK I will give this refactoring a try this week (or weekend) to see what we can do with it.

**Comment by devhkr** [comment]
Sorry folks, was AFK the whole weekend while having our discussions in mind.

Just a quick feeback from my side, again:

@Moshe-Immerman 
What do you mean by 
>in terms of resources I am of the belief they should be inlined e.g. Under the Docker images section we have both awesome docs/videos with tags and awesome software)

`Useful Resources` will be split up then? In my opinion, we should have two main sections (like `awesome-java`):
- Tools
- Useful Resources

@Moshe-Immerman @veggiemonk 
Instead of "Ancient, Archive...", how about `Legacy tools` ? So, we can list like Docker Toolbox etc.

Have a good start in the new week. TTYL

**Comment by veggiemonk** [comment]
@devhkr @Moshe-Immerman Agree with `Legacy` instead of `ancient`

**Comment by Moshe-Immerman** [comment]
How about we leave the resources section (along with it's icons) for another time/issue?

What about just these icons:

Commercial
Beta
Windows 
OSX

i.e. By default, we assume all tools support linux and possibly Windows and/or OSX, if they don't support Linux only then do we indicate which platform it targets instead

**Comment by veggiemonk** [comment]
this is done
