### ISSUE TITLE
Add Reddit docker community

### ISSUE THREAD

**Issue by jvmauricio** [veggiemonk/awesome-docker#402]
Hi,

I would like to add a link.

**COMMUNITIES AND MEETUPS - ENGLISH**:

**https://www.reddit.com/r/docker/ - Reddit Docker Community**:

**AUTHOR**:

Or directly write it:
```markdown
[REPO](https://github.com/AUTHOR/REPO) - DESCRIPTION. By [@AUTHOR](https://github.com/AUTHOR)
```

**Comment by agebhar1** [comment]
Hi @jvmauricio - thank you for your contribution!

You're welcome to open a PR too. Note, until we reordered the categories, all incoming PRs will be on hold.

The Awesome Docker Team

**Comment by jvmauricio** [comment]
Will do, thanks @agebhar1 !

**Comment by devhkr** [comment]
See PR #403
