### ISSUE TITLE
Docker Cheat Sheet

### ISSUE THREAD

**Issue by eon01** [veggiemonk/awesome-docker#407]
Hi,

I would like to add a link.

**REPO**:
https://github.com/eon01/DockerCheatSheet
**DESCRIPTION**:
Docker Cheat Sheet
**AUTHOR**:
@eon01

Or directly write it:
```markdown
+* [Docker Cheat Sheet](https://github.com/eon01/DockerCheatSheet) by [@eon01](https://github.com/eon01)  __MUST SEE__

```

**Comment by devhkr** [comment]
Hi @eon01

Thanks for sharing your version of Docker cheat-sheet.
We are in the middle of refactoring the list and all the sections. So we have to wait a little until this issue can be evaluated.
We will get back to you as soon as possible.

Thank you for your understanding.

The Awesome Docker Team

**Comment by eon01** [comment]
Appreciate your feedback. Thanks :)

**Comment by veggiemonk** [comment]
Hi, 

Due to the refactor, the project has been added in a separate commit: https://github.com/veggiemonk/awesome-docker/commit/5655f27fe7b0ca6070e39ffeffd418ce9f2083c4

Thank you for your PR, we hope that you can contribute to the quality of the projects on list in the future.

Have a good weekend
