### ISSUE TITLE
Clarify tagging purpose

### ISSUE THREAD

**Issue by devhkr** [veggiemonk/awesome-docker#446]
It seems to be still unclear when and for what purpose an icon should be used. I'm about to open a new PR updating the ```pull_request_template.md``` file.
Currently, we have the following icons with a clear description
- :face_with_head_bandage: indicates that the project is in beta phase
- :heavy_dollar_sign: indicates if one needs a paying subscription to use the project

for the following icon, I added a description
- :skull: indicates that the project is obsolete, but still worth mentioning it

following icons need more clarification
- :nerd_face: indicates ...
- :sunglasses: indicates ...
- :desktop_computer: indicates ...

**Comment by veggiemonk** [comment]
@devhkr It's true.

- :nerd_face: indicates that the project is meant to be used in a terminal, it's a CLI
- :sunglasses: indicates that the project is meant to be used in a web browser. it's a web app. (although the sunglasses are really misleading, any better solutions)
- :desktop_computer: indicates that the link is a website (not a github project) and it's probably closed source

All of the above can be changed according to use cases. It was just an idea that it would be a bit more joyful to use emojis on the list. You are totally right, if they don't make sense or if they are misleading, they are out!

**Comment by Moshe-Immerman** [comment]
@devhkr @veggiemonk Isn't the vast majority of the list CLI? Would it not be better to use them as the exception e.g. a CLI for a native web interface or a Web UI for a native CLI interface?

For web we could use 🌎  o 
For CLI we could use 🔤  or 🔡  or ⬛️  or ⌨️ 
For closed source: 🔑  or 🔒 or 🗝

**Comment by gesellix** [comment]
For web/link: 🔗
For CLI: 🤖

**Comment by veggiemonk** [comment]
I would remove the tag for CLI and for web based.... I see already in the PR it's a mess... They don't really add any value since it should be clear in the description what kind of tool it is.

**Comment by devhkr** [comment]
@veggiemonk totally agree with you. And I would like to emphasize [my comment](https://github.com/veggiemonk/awesome-docker/issues/393#issuecomment-320203782) on tagging. We really should stick to the minimum/essentials where we can definitively put some tags.

**Comment by agebhar1** [comment]
Beside

 :face_with_head_bandage: indicates that the project is in beta phase
 :heavy_dollar_sign: indicates if one needs a paying subscription to use the project
 :skull: indicates that the project is obsolete, but still worth mentioning it

I'm in favour to add the closed source indication by @Moshe-Immerman 

 :lock: indicates that the project sources are closed

--

So :face_with_head_bandage: :heavy_dollar_sign: :lock: might be possible :smile:

**Comment by devhkr** [comment]
It can also happen that a project is work in progress and a 🤕 seems to be the wrong symbol. How about using 🔨 ? It has two meanings, working and fixing. So, it can be used both as a symbol for WIP projects as well as beta projects.

**Comment by agebhar1** [comment]
@devhkr that's a good point :face_with_head_bandage: might be misleading. Beside of :hammer: there is :hammer_and_wrench: or :construction: ...

**Comment by gesellix** [comment]
Nice, I would prefer 🚧 or 🔨.

**Comment by devhkr** [comment]
@agebhar1 @gesellix 

I also had other symbols in mind. But 🔨 looks simple, compared to 🛠 . Like with 💀 and ☠️ .
In addition, 🚧 could only mean work in progress. However, a 🔨 could mean both building and fixing.

**Comment by agebhar1** [comment]
:thinking: ... that's right, but if we support 'fixing' we should be able to track open tasks/bugs. What did you think?

**Comment by devhkr** [comment]
Ah, I wasn't clear about my previous comment. My point is that if a project is released under beta, there'll be certain bugs to be fixed. So, that's why a 🔨. 
What do you mean by tracking open tasks/bugs? We can check the repo by its description. Once a project is released as a stable version, we can remove the symbol then.

Alternatively, we can use 🚧 for work in progress and 🔨 for beta projects. But as I said before, we should stick to the minimum as possible.

**Comment by gesellix** [comment]
I would also aim at reducing the amount of different symbols. I personally prefer 🚧, mostly due to its resemblance of old websites being "under construction". That would also include "WIP" as well as "Beta". I wouldn't oppose the 🔨, though, it also suggests something like "WIP" to me.

**Comment by veggiemonk** [comment]
👍  for 🚧

**Comment by veggiemonk** [comment]
Beta and WIP are roughly the same.. no need to differentiate them as far as I'm concerned

**Comment by agebhar1** [comment]
So these two should not change and we will be kept:

:heavy_dollar_sign: indicates if one needs a paying subscription to use the project
:skull: indicates that the project is obsolete, but still worth mentioning it

*Vote* by :+1: or :-1:

**Comment by agebhar1** [comment]
:face_with_head_bandage: indicates that the project is in beta phase
:lock: indicates that the project sources are closed

**Comment by agebhar1** [comment]
:face_with_head_bandage: Beta/WIP should be replaced by

:hammer: indicates that the project is in beta phase

Vote by :+1:

**Comment by agebhar1** [comment]
I suggest to add closed source

:lock: indicates that the project sources are closed

**Vote** by :+1: or :-1:

**Comment by devhkr** [comment]
We already have a :heavy_dollar_sign: for commercial tools which are considered as closed source projects. And as @veggiemonk also suggested that :desktop_computer: icon is for websites (not a GitHub project page) which are probably considered as closed source projects as well. We don't need the :lock: icon then. What do you think?

**Comment by devhkr** [comment]
Ok, you convinced me that we should use :construction: tag for WIP/Beta projects :smile: 
But still not convinced by the closed source one.
Can you name me please an example which project(s) could have such a tag?

**Comment by agebhar1** [comment]
Good point @devhkr the symbol :lock: is the same as in web browser if https is used with a valid certificate. Slack use the symbol for private channels ... so maybe we skip 'closed source' for the moment.

**Comment by devhkr** [comment]
I realized that lately. Sorry about that. Ok, we have then

💲  indicates if one needs a paying subscription to use the project
🚧  indicates that the project is in the work in progress/beta phase
💀  indicates that the project is obsolete, but still worth mentioning it

I'll open a new PR updating the 'README.md' and the 'pull_request_template.md'.

Thanks for your feedback guys and have a nice day 😃
