### ISSUE TITLE
remove `style.min.css`

### ISSUE THREAD

**Issue by agebhar1** [veggiemonk/awesome-docker#453]
Minified stylesheet `style.min.css` was introduced at e946c57200d5dff5923afcb4ef9eb5b89e704028 **meta tags and min css** as replacement of unminified version `style.css`. Unfortunately at 09ae203207252428709ccac20ec70c9f8bf6317a **Fix Table of Content** `style.css` was re-introduced in addition to minified version. Consequently both versions where requested.

I suggest to remove the minified version since
* both `style.css` and `style.min.css` are divergent
* hard to manually maintain `style.min.css` (don't forget to minify `style.css` each time it's updated)
* 16Kb (`style.css`) vs. 8.1Kb (`style.min.css`) doesn't matter

Please vote via:
* :+1: remove
* :-1: keep (implies update of `style.min.css`)

**Comment by gesellix** [comment]
Though I normally don't agree with arguments like

> 16Kb (style.css) vs. 8.1Kb (style.min.css) doesn't matter

I think in this case the maintenance aspect is more important. So looking at the current state my vote goes for 👍 .

Yet, I would try to find an automated way of updating the minified version. That would probably imply some more advanced configuration of Travis-CI and I'm not sure if we need such a setup only for some optimisation.

**Comment by agebhar1** [comment]
You're right @gesellix size is a bad argument :smiley:.

If we don't care about the Travis-CI setup (only @veggiemonk might be able). Each check on Travis-CI builds the minified version of `sytle.css` and push automatically to branch `gh-pages`. Consequently the default view must be changed to `gh-pages`. As a result the minified version could be removed from the `main` branch and is a build artefact.

**Comment by gesellix** [comment]
:-)

I agree, the minified version should be considered as a build artifact!

**Comment by veggiemonk** [comment]
there is no point at being super efficient. Removing the min.css is better. Ease of maintenance is better for now. 

Also for info, the `gh-pages` is useless. Everything is in master, it's much simpler to manage like that. And the list is automatically updated because it fetch and converts the readme while loading the page.
