### ISSUE TITLE
docker-client - TypeScript Docker API client

### ISSUE THREAD

**Issue by masaeedu** [veggiemonk/awesome-docker#468]
Hi,

I would like to add a link.

**REPO**:
https://gitlab.com/masaeedu/docker-client

**DESCRIPTION**:
Docker API client in TypeScript, automatically generated from Swagger API definition in https://github.com/moby/moby repository.

**AUTHOR**:
masaeedu (me)

**Comment by veggiemonk** [comment]
@masaeedu thank you for your contribution. This project will be very useful 👍 
See the PR #471
