### ISSUE TITLE
Add -  Docker Flow Proxy 

### ISSUE THREAD

**Issue by Vad1mo** [veggiemonk/awesome-docker#477]
Hi,

I would like to add a link.

**REPO**:
https://github.com/vfarcic/docker-flow-proxy

**DESCRIPTION**:
Docker Flow Proxy,  Easy way to reconfigure proxy every time a new service is deployed, or when a service is scaled. HAProxy based. Works with Swarm out of the box.

**AUTHOR**:
https://github.com/vfarcic

Or directly write it:

```markdown
[Docker Flow Proxy](https://github.com/vfarcic/docker-flow-proxy) - Easy way to reconfigure proxy every time a new service is deployed, or when a service is scaled. HAProxy based. Works with Swarm out of the box. By [@vfarcic](https://github.com/vfarcic)
```

**Comment by vegasbrianc** [comment]
Thanks @Vad1mo Created PR #480 for docker-flow-rpxy
