### ISSUE TITLE
Docker Flow Swarm Listener

### ISSUE THREAD

**Issue by Vad1mo** [veggiemonk/awesome-docker#478]
Hi,

I would like to add a link to **Docker Flow Swarm Listener**

**REPO**:
https://github.com/vfarcic/docker-flow-swarm-listener

**DESCRIPTION**:
Docker Flow Swarm Listener project is to listen to Docker Swarm events and send requests when a change occurs.

**AUTHOR**:
[@vfarcic](https://github.com/vfarcic)

Or directly write it:

```markdown
[Docker Flow Swarm Listener](https://github.com/vfarcic/docker-flow-swarm-listener) :construction: - Docker Flow Swarm Listener project is to listen to Docker Swarm events and send requests when a change occurs.. By [@vfarcic](https://github.com/vfarcic)
```

**Comment by vegasbrianc** [comment]
@Vad1mo PR #482 Created

**Comment by veggiemonk** [comment]
@vegasbrianc thanks 👍
