### ISSUE TITLE
Docker Flow Monitor

### ISSUE THREAD

**Issue by Vad1mo** [veggiemonk/awesome-docker#479]
Hi,

I would like to add a link to **Docker Flow Monitor**

**REPO**:

https://github.com/vfarcic/docker-flow-monitor

**DESCRIPTION**:

Reconfigure Prometheus every time a new service is deployed, or when a service is updated. 

**AUTHOR**:

Or directly write it:
```markdown
[Docker Flow Monitor](https://github.com/vfarcic/docker-flow-monitor) - Reconfigure Prometheus every time a new service is deployed, or when a service is updated. By [@vfarcic](https://github.com/vfarcic)
```

**Comment by vegasbrianc** [comment]
@Vad1mo Cool tool! I need this as well. PR #481 has been added for the Docker Flow Monitor
