### ISSUE TITLE
Docker Securitiy - Quick Reference book

### ISSUE THREAD

**Issue by binarymist** [veggiemonk/awesome-docker#520]
Hi.

I would like to add a link.

Would you be interested in including my Docker Securitiy - Quick Reference book?

https://binarymist.io/publication/docker-security/

If so, I'll sub a PR.

Thanks.

**Comment by veggiemonk** [comment]
Hi @binarymist,

Yes please make a PR, this is a really useful resources.

You add it there: https://github.com/veggiemonk/awesome-docker#security-1

**Comment by binarymist** [comment]
In this podcast (http://www.se-radio.net/2017/05/se-radio-episode-290-diogo-monica-on-docker-security/) I interviewed Docker Security Team Lead, it's also an excellent resource. Let me know if you would like it included and where, if you would.
Thanks.

**Comment by veggiemonk** [comment]
@binarymist That's a valuable resource. You can add it too, just mention that it is a podcast and not an article.
Thank you
