### ISSUE TITLE
Change list title

### ISSUE THREAD

**Issue by veggiemonk** [veggiemonk/awesome-docker#581]
Hi all,

Do you think we should adapt and make this repo a more OCI (https://www.opencontainers.org/) rather than just "Docker" ?

So the list would be "A curated list of open container resources and projects"

What do you think about that? What are the implication of this?

**Comment by dmitrytokarev** [comment]
Well then the repo will need to be renamed. Probably best is to create another list: awesome-containers?

**Comment by agebhar1** [comment]
I like the idea to be more open and not only focused on docker. @dmitrytokarev create another with the initial content of »awesome-docker«? There are already some »awesome-container« on GitHub. Pro for renaming this list is, it redirects everyone from an old bookmark to the new repository. There might be a short sentence of the history of this awesome list at the top.

**Comment by veggiemonk** [comment]
What do you think about this? 
* keeping the list as "awesome-docker" since it's popular and referenced to many places
* we extend to content to more than just docker by adding new labels and categories (emojis?)
* we clearly state when the content is docker specific and when it is not.

The awesome list called [awesome-linux-containers](https://github.com/Friz-zy/awesome-linux-containers) doesn't have a lot of attention. And in the name there is "Linux" which would exclude many project running on windows. 

If we want to create a new list, let's make it a organisation on its own. 

There is a lot of options, let us know what you think. There is no right or wrong answer.

**Comment by veggiemonk** [comment]
So far the ideas are:

* keep the name `awesome-docker`
* extend the current list with labels, categories, etc.
* create a new list
* split into sub-lists
* create a family of list e.g. `awesome-containers-<sublist>`, where `<sublist>` can be empty, docker, orchestration.
* include a short section of very popular related projects (LXD, LinuxKit, InfraKit, Kubernetes, Unikernels etc..)

What are the concerns?

* amount of work: we might overwhelm ourselves with the sheer amount of tools and pace the community is evolving
* Overlap with awesome-kubernetes, and https://landscape.cncf.io/

**Comment by veggiemonk** [comment]
Ok, I had a few ideas and this got out of hand quickly....

* The fact that we have only one page makes it's easy to press `CTRL/CMD + F` to search for keywords. So splitting into many lists might be more a hassle just for the sake of having clearly defined category but that's just my personal opinion. I would like to have one list with filtering and sorting.

* The way to display the content is important. One thing I really like about the [CNCF landscape](https://landscape.cncf.io/) is the ability to apply many filter and sort order. This requires some data to be stored, this is why I started working on this a while ago: https://github.com/veggiemonk/awesome-docker/tree/master/data

* The list is a `README.md` of a github repository, converting it into a website is kind of a big change. But that change can prevent us from being overwhelmed by the amount of projects that we need to evaluate if we have tools and the data.

* I want to keep the commitment low. Like a side project, not a full time job. So we are talking automation. [We can already gather some data from github](https://github.com/veggiemonk/awesome-docker/blob/master/data/table.md). For the documentation, the installation instructions and a "try it yourself" example, we can create a form to store it. So when a PR is created, some fields of the PR are parsed. If the field are not filled, they will appear blank in the table. So we can quickly see what are the projects that are higher quality than others. Let me know what kind of data would you like to see in the table. Like how many starts since last month/week ? Number of open issue? number of PR? and so forth...

* When the scope of a project is too big, it is time to scope it down and iterate over. Everybody seems to agree that we should include all OCI related projects. Instead of curating a list, we gather every projects and **their metadata** in order to categorize/list them in the best way possible. Then we curate predefined filters such as "docker-only", "windows-only", "osx-only", "for-developers", "for-sysadmin", "for-learning", "beginner-friendly" and so on...

* Let's keep the `Where to start` section and stay beginner-friendly. Many projects are too complex to understand just by reading a description. Containers are completely new concept for a lot of people and we should aim at making their learning curve less steep. 

Let me know your thoughts...

**Comment by agebhar1** [comment]
@veggiemonk, will leave my feedback at weekend

**Comment by veggiemonk** [comment]
Made a little something to try things out (see #584)

**Comment by veggiemonk** [comment]
Still fixing the #584 with the sorting...

I think having those data being fetch automatically once a day is good enough. 

We still need to think of something to integrate the "where to start" section.

**Comment by veggiemonk** [comment]
Gradually getting there.... it needs a few more features though before we can migrate
