### ISSUE TITLE
Help awesome-docker to be presented at DockerCon EU 2018

### ISSUE THREAD

**Issue by veggiemonk** [veggiemonk/awesome-docker#586]
Hi everybody,

I'm planning to do a lightening talk in order to present awesome-docker.
I need your help to build the content of the presentation.
As it is born from the contribution of more than 200 people, I think it is only fair that it represents that.
Could you explain a bit what does awesome-docker means to you?
How can it help other people?
How would like other people to contribute to it?
Anything else?

It's been a few years since this project exists. 
It is always nice to interact and build this thing with you.
I want to thank you all very much.
I really appreciate you sticking around over the years 👍

**Comment by dmitrytokarev** [comment]
@veggiemonk It's been to see this project thrive and grow organically while keeping up with the community developments.
I think awesome-docker is "the go to" resources in terms of evaluating technologies related to docker/containers. And for newcomers and for seasoned professionals it's THE place to find new projects - simply put one just need to google/search for "awesome docker" and it's all you need, it's all here nicely organized. Big props to all contributors ❤️

**Comment by vegasbrianc** [comment]
I always try to explain Awesome Docker as the best resource for all things Docker. We track different aspects of the stack from OS, Network on up. I always try to encourage people to submit what they are working on to get exposure as I mention how many stars the project has.

@veggiemonk I am more than happy to help with this!

**Comment by veggiemonk** [comment]
I think I just find the title of the talk: `the best resource for all things Docker: Awesome Docker`

Thanks @vegasbrianc 👍 

What do you think?

I want to do a lightening talk but there would be enough material for a full 20 min talk. How long are the talks anyway?

**Comment by agebhar1** [comment]
Sorry for beeing late. Both @dmitrytokarev and @vegasbrianc hit the nail on the head. It is **the** resource for Docker (Container in future). Sadly, I can't contribute anything new 😞

**Comment by veggiemonk** [comment]
Thanks @agebhar1 
You've contributed in a lot of ways to this project. Thank you for that.

**Comment by vegasbrianc** [comment]
@veggiemonk I will be going to DockerCon EU as well 👍
