### ISSUE TITLE
Github markdown doesn't use reference anymore

### ISSUE THREAD

**Issue by veggiemonk** [veggiemonk/awesome-docker#588]
Link reference used to be of the kind
```
[@spotify][spotify]

[sportify]: https://github.com/spotify
```

But now it is left unprocessed. 😞

Anybody has any idea how to deal with this ?

**Comment by agebhar1** [comment]
I can't find any indication for a change or markdown processing either on https://github.com/github/markup nor https://githubengineering.com/. Also the the GFM specs still contains [reference links](https://github.github.com/gfm/#full-reference-link). Hopefully it's temporarily.

**Comment by veggiemonk** [comment]
It was my fault but Stacey from Github found the issue.

```
Hey Julien,

It looks like the following link on line 709 as parenthesis around the link which seems to be breaking the subsequent references:

[ContainX](https://github.com/ContainX)

Changing the syntax to [ContainX] : https://github.com/ContainX should fix it up!

Cheers
Stacey 
```

Fixes in https://github.com/veggiemonk/awesome-docker/commit/3c57f60e1201192d15e20ed2a6f994c91d41e3c9
