### ISSUE TITLE
Github Slack Integration

### ISSUE THREAD

**Issue by alancapc** [veggiemonk/awesome-docker#604]
Hi,

Can the owner install Github Slack integration, please?

This way people can receive any updates being made in here over slack.

[Install GitHub App integration link](https://slack.github.com/github/install/5487021/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmlnZ2VyX2lkIjoiNDIyMjI2ODA2NjQxLjE4NDU3OTg0MTQ0MC40ZTg1ZDFjZTMyZTEzZDAzODQ1YWM4YjE2MDgwYjIwZiIsImlhdCI6MTUzNTEyMzc3NywiZXhwIjoxNTM1MTI3Mzc3fQ.rMpmJmjSUIQBwRLLDGV-klKfi9H2z3gO8E_kk1Nxjwo)

**PROBLEM**
![image](https://user-images.githubusercontent.com/7346073/44592813-94151c80-a7b9-11e8-82bb-c93d686363b8.png)

**Comment by veggiemonk** [comment]
@alancapc Sure, but which slack channel are you using ?

**Comment by veggiemonk** [comment]
@alancapc the reason I asked is because I tried to click on the link but got `An unexpected error occured`

**Comment by veggiemonk** [comment]
@alancapc ok.... what do we do now ?

**Comment by vegasbrianc** [comment]
@alancapc @veggiemonk Maybe it would be good to understand the use case a bit better. It could be possible we handle this another way.

**Comment by veggiemonk** [comment]
@vegasbrianc Sure, what do you propose ?

**Comment by alancapc** [comment]
Sorry for the late reply, maybe if I create a quick .gif of the use case it would help understanding the use 
case? 

Steps to reproduce desired result:

1.  On Slack, add/install "Github" app.
![image](https://user-images.githubusercontent.com/7346073/44717102-09336b00-aab4-11e8-829b-9acd74171908.png)
2.  On Slack, go to "Github" app to (can do this from anywhere, but doing so here for the sake of keeping one scope):
![image](https://user-images.githubusercontent.com/7346073/44717332-9f679100-aab4-11e8-862f-4563bdd91bd6.png)
3. From Github app, subscribe to a project (One that can be used for comparison is [docker/compose](https://github.com/docker/compose)).
![image](https://user-images.githubusercontent.com/7346073/44716813-40554c80-aab3-11e8-8b74-e0342ad298c7.png)
4. **Output:** Any updates on docker/compose project hosted on Github will be reflected as notifications on Slack:
![image](https://user-images.githubusercontent.com/7346073/44717575-40564c00-aab5-11e8-8f73-4bd37b3011af.png)
5. **Clean up:** If you don't want to follow docker/compose (I do as it doesn't seem ready for production on windows just yet) just unsubscribe from it:
Unsubscribe to notifications for a repository:
`/github unsubscribe owner/repository`

To understand the scenario going through these steps will give you a fairly good idea of how I planned on receiving[ veggiemonk/awesome-docker](https://github.com/veggiemonk/awesome-docker) notifications on slack.

I will think of why it cannot be done from [veggiemonk/awesome-docker](https://github.com/veggiemonk/awesome-docker) just yet and how this can be changed, as soon as I do so will get back.

Thanks !

**Comment by veggiemonk** [comment]
@alancapc @vegasbrianc Does one need to install the slack app on github or the github app on slack. I'm confused....

**Comment by veggiemonk** [comment]
Reopen the issue if still relevant
