### ISSUE TITLE
Add new project to the list

### ISSUE THREAD

**Issue by jgbradley1** [veggiemonk/awesome-docker#621]
Hi,
I would like to add a link. This project is in the middle of [getting picked up](https://projects.eclipse.org/proposals/eclipse-theia) by Eclipse. Definitely worth adding to the list in my opinion.

**REPO**: [Eclipse Theia IDE](https://github.com/theia-ide/theia)

**DESCRIPTION**: A cloud & desktop IDE.

**AUTHOR**: TypeFox, Ericsson and Red Hat

**Comment by agebhar1** [comment]
Also from my side, thank you @jgbradley1. Closed by #622.
