### ISSUE TITLE
Adding a new item to "where to start"

### ISSUE THREAD

**Issue by takacsmark** [veggiemonk/awesome-docker#657]
Hi Team, 

I'm very happy I bumped into your list on GitHub, the list is really awesome, a lot of valuable projects here.

I don't know if you are open for contributions on the "Where to start" side, I have a comprehensive tutorial series with 10 lengthy posts on my blog and 4 hours of video tutorials on Youtube dedicated to Docker. It's quite popular, especially with beginners.

Please feel free to check it out at [https://takacsmark.com/ ](https://takacsmark.com/ )and [https://www.youtube.com/takacsmark](https://www.youtube.com/takacsmark).

Please let me know what you think, I'd be really happy to contribute.

Cheers, 

Mark

**Comment by veggiemonk** [comment]
Hi @takacsmark,

If there is a git repo to learn or to teach docker, then yes, a PR is more than welcome.
Otherwise, it is not really interesting.

Thank you for opening this issue. Thanks to you, we got a change to clean up some old or irrelevant resources. See #658  😄

**Comment by takacsmark** [comment]
Hi @veggiemonk, thanks your response. My stuff is tutorials and videos, not one repo, so I guess it won't make it to the list. Anyways, you have a cool repo, maybe I'll have something in the future.

Cheers,

Mark

**Comment by veggiemonk** [comment]
Hi @takacsmark,
You are welcome to contribute anytime. If you create a repo with "how to get started with Docker and containers", it would definitely make it to the list 😄 

Cheers,

Julien
