### ISSUE TITLE
CI tests all links for each PR

### ISSUE THREAD

**Issue by dmitrytokarev** [veggiemonk/awesome-docker#716]
@veggiemonk i think we need to rework the CI logic for this project.
I think for new PRs only changes need to be tested. That way builds would be way faster too.
And all links can be tested nightly and maintainers may opt to be notified for failures and decide to open PR to fix issues.

The reason is that contributors are blocked if any of the links fail from the whole of README.md. Yes, maintainers have the privilege ignore CI failures and merge but it’s just bad experience for everybody. I merge without that happy feeling that all tests passed, you know that feeling right? ;)

In the case of PR #715 i added lazydocker project and some other link failed.

Please see PR #715 comment https://github.com/veggiemonk/awesome-docker/pull/715#issuecomment-508440502 for details

**Comment by veggiemonk** [comment]
Hi @dmitrytokarev thank you for contributing :D 

I agree with you. Do you know how to test only the changes ?
Would you like to take care of that ?

**Comment by dmitrytokarev** [comment]
It's doable. I would be able to look into this late July early August.

**Comment by veggiemonk** [comment]
Great! Let's sync up then. We could have a video call and discuss it.

Let's keep this open as a reminder.

Thanks

**Comment by veggiemonk** [comment]
ping @dmitrytokarev :)

**Comment by dmitrytokarev** [comment]
It's been a while. I'll start working on this.

**Comment by veggiemonk** [comment]
This was fixed in the previous commits. Let's not fix something that is not broken (anymore :))

**Comment by veggiemonk** [comment]
The tests are now fixed @dmitrytokarev 
So can we close this ?

**Comment by dmitrytokarev** [comment]
Agreed.
