### ISSUE TITLE
Maintenance page

### ISSUE THREAD

**Issue by wickerlabs** [veggiemonk/awesome-docker#739]
Hi,

I would like to add a link.

**REPO**: https://github.com/wickerlabs/maintenance

**DESCRIPTION**: A simple maintenance page in a simple docker image.

**AUTHOR**: @wickerlabs

**Comment by veggiemonk** [comment]
Hi @wickerlabs,

Thank you very much for contributing. 
I checked the repository and it is well done and documented. However, this repository (awesome-docker) is meant to gather resource about containers not really about application living inside those containers.
I would recommend you check those awesome list: https://github.com/Kickball/awesome-selfhosted#readme

And if this isn't the right list, you may very well find one that suits your need here: https://github.com/sindresorhus/awesome#readme

Best of luck in the future and do not hesitate to come back to share a project related to containers
