### ISSUE TITLE
Recommendations For SaaS subscriptions

### ISSUE THREAD

**Issue by bryantmakesprog** [veggiemonk/awesome-docker#746]
I'm actually looking for a recommended software for hosting SaaS software in containers.

Basically:

- users sign up
- container gets spun up
- domain pointing to container populates in proxy
- subscription ends, container goes down

Looks like all the parts are there if someone wanted to build it from scratch, but surely there is an existing software?

**Comment by veggiemonk** [comment]
Hi @bryantmakesprog I don't know of anything like that.
You might have more chances to look into this: https://github.com/Kickball/awesome-selfhosted

Otherwise, just check out the PaaS section and write code to glue things up.

I hope it helps 😄
