### ISSUE TITLE
Awesome Docker Compose

### ISSUE THREAD

**Issue by iedmrc** [veggiemonk/awesome-docker#748]
Hi,

I would like to add a link.

**REPO**: https://github.com/iedmrc/awesome-docker-compose

**DESCRIPTION**: Awesome Docker Compose files repository. Run a well-prepared applications stack with just a single command. This repository consists of useful docker-compose files. A well-prepared Docker stack can be run with just a single `docker-compose up -d` command thanks to the docker-compose files in this repository.

**AUTHOR**: https://github.com/iedmrc

Or directly write it:
```markdown
[REPO](https://github.com/iedmrc/awesome-docker-compose) - Awesome Docker Compose files repository. Run a well-prepared applications stack with just a single command.
. By [@AUTHOR](https://github.com/iedmrc)
```

**Comment by veggiemonk** [comment]
Hi @iedmrc 
I could not find that awesome list on the original one: https://github.com/sindresorhus/awesome#readme

When the entry is accepted there, you can come back here and we will add it to the list. 

Thank you
