### ISSUE TITLE
Remote dnsmasq updater

### ISSUE THREAD

**Issue by moonbuggy** [veggiemonk/awesome-docker#797]
Hi,

I would like to add a link.

I was going to fork and PR but I found myself unsure of whether it would be better suited in the Networking or Reverse-Proxy category. I was also unsure about whether anyone else might even find it useful - possibly I've missed something obvious and solved a problem no one else but me has. (Also, it's a little bit intimidating looking at a category you think your little Python script might belong to and seeing that category largely consists of full-blown network fabrics. :))

If you think it's worthwhile to add my small project to the list, and can suggest the most appropriate category, I'm happy to go ahead and do the PR. If it's not awesome enough, that's fine too, no skin off my nose. My name resolution problems are solved either way (even if they are problems of my own making due to missing an obvious existing solution :)).

**REPO**: https://github.com/moonbuggy/docker-dnsmasq-updater

**DESCRIPTION**: Update a remote dnsmasq server with Docker container hostnames

**AUTHOR**: [moonbuggy](https://github.com/moonbuggy)

**Comment by veggiemonk** [comment]
Hi @moonbuggy ,

Thank you for opening an issue. 
I think it would be best suited in Reverse-Proxy. I think it is an interesting project. 

Just a note, it took me a while to figure out why I would use that but the documentation is good!
That makes it all worthwhile. 

Congratulations on that project. 

Please make a PR we would love to have your project on the list 😄

**Comment by moonbuggy** [comment]
> Just a note, it took me a while to figure out why I would use that [..]

That's related to the reason I wondered if I'd missed an existing solution, I was surprised I didn't find something that already did this, so I figured either I missed something or not many other people care about automating LAN hostnames for containers. There's some irony either way, if my laziness about editing hosts files caused me to put more time in to a completely unnecessary Python script than I'd have put into editing hosts files manually in the first place. :)

I'm kinda curious to see if anyone else does find it useful or not, and having it on this list should, if nothing else, satisfy that curiosity. One way or the other. :) With a bit of luck, at least some others will have a use for it and waving it around in public will have benefit beyond merely satisfying my curiosity.

Anyway, I've submitted the PR, thanks for your time and attention.

**Comment by veggiemonk** [comment]
> There's some irony either way, if my laziness about editing hosts files caused me to put more time in to a completely unnecessary Python script than I'd have put into editing hosts files manually in the first place. :)

Hahaha, I thought about that, I guess nobody dared to automate that part. Congratulations on being the first 😄
