### ISSUE TITLE
Link Request: Infrastructure as Code for Keycloak

### ISSUE THREAD

**Issue by klg71** [veggiemonk/awesome-docker#841]
Hi,

I would like to add a link. However im quite unsure if this repository fits in here :)

**REPO**: https://github.com/klg71/keycloakmigration

**DESCRIPTION**: Provide Infrastructure as Code for KeyCloak, inspired by LiquiBase

**AUTHOR**: klg71

**Comment by veggiemonk** [comment]
Hi @klg71 ,

It seems it is a plugin for Keycloack, that is assuming people know what Keycloack is. 
I'm not sure what is the relation to Docker/container ? 
Could you explain how would you use it in your workflow ?
It is hard to grasp what problem does it solve when using containers :D
The project seems well maintained with lots of documentation and examples. 
We would love to help you describing your project so it can reach more people who find that useful.

**Comment by klg71** [comment]
Hi veggiemonk.

Thanks for your answer!
My thaughts of including keycloakmigration in this repository were that it doesn't just contain docker stuff but also a lot of devops related content and that my repository could therefore be a good fit.
If you plan to deploy keycloak in a docker container you might find this plugin useful as it helps organizing and deploying your keycloak configuration.
But I might be mistaken on this one and the regard is actually too far away.

**Comment by veggiemonk** [comment]
We don't really have a category for that and I'm not sure that if someone using docker would find that useful unless they also are using keycloak and have that kind of issue.

I think it is a good project but I don't know where to put it. 
Also it is more related to keycloak than docker. 

Docker recently made https://github.com/docker/awesome-compose
You might have more chances there.

Let me know what you think

**Comment by klg71** [comment]
Alright thank you for the provided link I will look into it :)
