### ISSUE TITLE
Add Docker.Registry.DotNet (C#) Registry Client

### ISSUE THREAD

**Issue by Jaben** [veggiemonk/awesome-docker#885]
Hi,

I would like to add a link.

**REPO**: https://github.com/ChangemakerStudios/Docker.Registry.DotNet

**DESCRIPTION**: .NET (C#) Client Library for interacting with a Docker Registry API (v2)

**AUTHOR**: rquackenbush

**Comment by mash1t** [comment]
Hey @Jaben,
it would be great if you could open a pull request including the mentiones link following our guidelines (you'll see them on PR creation).
The link should be added to the category "registry" (link: https://github.com/veggiemonk/awesome-docker#registry).

**Comment by Jaben** [comment]
Absolutely

**Comment by Jaben** [comment]
Done -- PR #887 -- closing this issue.
