### ISSUE TITLE
Show unmaintained projects in different color/icon

### ISSUE THREAD

**Issue by pvtmert** [veggiemonk/awesome-docker#890]
Hi there,

The list is versatile and contains lots of projects, which is good but I've noticed some of the projects stopped being maintained relatively long time ago (~4 years at the time of writing)

I can make them a-bit faded/grayed out or adding clock icon (like dollar sign)

What do you think?

**Comment by mash1t** [comment]
Hey @pvtmert you're always welcome to add the skull icon to discontinued/non-maintained entries and open a pull request for review 👍

**Comment by pvtmert** [comment]
@mash1t cool, thanks. checking out contributing.md :)
