### ISSUE TITLE
Add Krane

### ISSUE THREAD

**Issue by david-castaneda** [veggiemonk/awesome-docker#923]
Hi,

I would like to add a link.

```markdown
[Krane](https://github.com/krane/krane) - Toolset for working with containers. By [@david-castaneda](https://github.com/david-castaneda)
```

**Comment by dmitrytokarev** [comment]
@david-castaneda Thank you for opening the issue. You could just open the MR to add it. See https://github.com/veggiemonk/awesome-docker/blob/master/.github/CONTRIBUTING.md
I looked at the github project and it's missing a license. Is it intended? If not, this page may help you choose a license:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#:~:text=You're%20under%20no%20obligation,derivative%20works%20from%20your%20work.

**Comment by david-castaneda** [comment]
@dmitrytokarev I'll submit a merge request then, thanks!

I opened this issue as per [Adding to the list](https://github.com/veggiemonk/awesome-docker/blob/master/.github/CONTRIBUTING.md#i-want-to-share-a-project-what-should-i-do) 😄

**Comment by mash1t** [comment]
see https://github.com/veggiemonk/awesome-docker/pull/924
