### ISSUE TITLE
bocker(2) dead?

### ISSUE THREAD

**Issue by StefanWetterActiware** [veggiemonk/awesome-docker#951]
Hi,

the "bocker(2)"-Projects seems to be dead. Last commit 2 years ago containing just the hint "i have no time for this".

I suggest you add this wunderful skull there?

Greetings from germany
Stefan

**Comment by mash1t** [comment]
Hey @StefanWetterActiware,
thank you for the hint, i created a PR (https://github.com/veggiemonk/awesome-docker/pull/952) for you.
You're always welcome to create a PR yourself, we'll then have a look at the changes and review them.
