### ISSUE TITLE
Visual docker-compose.yaml code generator.

### ISSUE THREAD

**Issue by corpulent** [veggiemonk/awesome-docker#979]
Hi,

I would like to add a link.

**REPO**:
https://github.com/nuxxapp/nuxx

**DESCRIPTION**:
Visually generate docker-compose.yaml code with drag-n-drop.  Here is an example https://app.nuxx.io/?recipe=EgbILm1qSA.

**AUTHOR**:
https://github.com/corpulent

**Comment by mashb1t** [comment]
Hey @corpulent

thank you for the idea.
You're welcome to create a new merge request, follow its template step by step and reference/close this issue afterwards.
